### ISSUE TITLE
Memory leak after deserializing in multiple threads

### ISSUE THREAD

**Issue by x-hgg-x** [rkyv/rkyv#277]
The following program leaks memory after deserialization:

`Cargo.toml`:

```toml
[dependencies.rayon]
version = "1.5.2"

[dependencies.rkyv]
version = "0.7.38"
default-features = false
features = ["std", "strict", "size_64", "validation", "archive_le"]

[dependencies.bytecheck]
version = "0.6.8"
default-features = false
```

`main.rs`:

```rust
use rayon::prelude::*;
use rkyv::ser::{serializers::*, Serializer};
use rkyv::Deserialize;

use std::sync::Mutex;
use std::time::Duration;

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
#[archive_attr(derive(bytecheck::CheckBytes))]
#[derive(Debug, Default)]
pub struct S {
    id: String,
    bytes: Vec<u8>,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
#[archive_attr(derive(bytecheck::CheckBytes))]
#[derive(Debug, Default)]
pub struct Data {
    v: Vec<S>,
}

fn serialize() -> Vec<u8> {
    let data = Data {
        v: (0..1000)
            .map(|i| S {
                id: i.to_string(),
                bytes: vec![Default::default(); 1 << 20],
            })
            .collect(),
    };

    let mut bytes = Vec::new();
    let mut serializer = CompositeSerializer::new(
        WriteSerializer::new(&mut bytes),
        <FallbackScratch<HeapScratch<1024>, AllocScratch>>::default(),
        SharedSerializeMap::default(),
    );
    serializer.serialize_value(&data).unwrap();
    bytes
}

fn deserialize(lock: &Mutex<()>, bytes: &[u8]) {
    // The Mutex here is to ensure that only one deserialization is occuring at the same time 
    let _guard = lock.lock().unwrap();
    {
        let archived = rkyv::check_archived_root::<Data>(bytes).unwrap();
        let _: Data = archived.deserialize(&mut rkyv::Infallible).unwrap();
    };
}

fn main() {
    let lock = Mutex::new(());

    {
        let bytes = serialize();

        println!("start");
        std::thread::sleep(Duration::from_secs(2));

        // No memory leak occurs in single thread
        // let iter = (0..8).into_iter();
        let iter = (0..8).into_par_iter();

        iter.for_each(|_| deserialize(&lock, &bytes));
    }

    // Memory is not freed before the end of the program after deserializing in multiple threads
    println!("end");
    std::thread::sleep(Duration::from_secs(5));
}
```
