### ISSUE TITLE
Add extra discription keywords

### ISSUE THREAD

**Issue by flukejones** [rkyv/rkyv#425]
Not an issue with the crate, but more with trying to find it again after forgetting the name.

I tried many keywords like: tiny, small, compact, no-std, fast etc. Mostly because those are what I seemed to remember about it. I wasn't able to find until I searched "zero copy" however.

**Comment by djkoloski** [comment]
Right now the keywords and categories for rkyv on crates.io are:

```toml
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
```

So it seems like you should have had success by searching for `no-std`. While rkyv strives to be tiny, small, compact, and fast, those are relatively subjective measures and I'd prefer to stick to any fact-based information about the crate. What keywords would you suggest?
