### ISSUE TITLE
rkyv is actually slower with deserialization, did I do something wrong?

### ISSUE THREAD

**Issue by peterwilli** [rkyv/rkyv#542]
I was surprised to see that rkyv performed worse, even in deserialization

Cargo version: cargo 1.81.0 (2dbb1af80 2024-08-20)
Device: MacBook Air M2 16GB RAM

Here's my benchmark output:

```
bitcode serialize: 1.42ms
bitcode deserialize: 15.29µs
rkyv serialize: 4.26ms
rkyv deserialize:  721.58µs
```

I created the following PoC project to test it out:

```rs
use std::time::Instant;

use bitcode::{Decode, Encode};
use rand::{thread_rng, RngCore};
use rkyv::{Archive, Deserialize as RkyvDeSerialize, Serialize as RkyvSerialize};

#[derive(Encode, Decode, Archive, RkyvSerialize, RkyvDeSerialize)]
#[archive(
    // This will generate a PartialEq impl between our unarchived and archived
    // types:
    compare(PartialEq),
    // bytecheck can be used to validate your data if you want. To use the safe
    // API, you have to derive CheckBytes for the archived type:
    check_bytes,
)]
struct FakeChunk {
    pub data: Vec<u8>,
    pub tag: Vec<u8>,
}

fn main() {
    let mut data = vec![0u8; 1024 * 30];
    let mut tag = vec![0u8; 32];
    thread_rng().fill_bytes(&mut data);
    thread_rng().fill_bytes(&mut tag);
    let test_chunk = FakeChunk { data, tag };

    {
        let now = Instant::now();
        let bytes = bitcode::encode(&test_chunk);
        println!("bitcode serialize: {:.2?}", now.elapsed());
        let now = Instant::now();
        let obj: FakeChunk = bitcode::decode(&bytes).unwrap();
        println!("bitcode deserialize: {:.2?}", now.elapsed());
    }
    {
        let now = Instant::now();
        let bytes = rkyv::to_bytes::<_, { 1024 * 40 }>(&test_chunk).unwrap();
        println!("rkyv serialize: {:.2?}", now.elapsed());
        let now = Instant::now();
        let archived = rkyv::check_archived_root::<FakeChunk>(&bytes[..]).unwrap();
        println!("rkyv deserialize:  {:.2?}", now.elapsed());
    }
}
```

Cargo toml:

```toml
[package]
name = "serializer_benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitcode = "0.6.3"
postcard = { version = "1.0.10", features = ["alloc"] }
rand = "0.8.5"
rkyv = { version = "0.7.45", features = ["validation"] }
```
